# Generated by Django 5.0.11 on 2025-02-02 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entryregime',
            name='regime',
            field=models.TextField(blank=True, null=True, verbose_name='Режим въезда в РФ'),
        ),
    ]
