# Generated by Django 5.0.11 on 2025-02-05 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_alter_entryregime_regime'),
    ]

    operations = [
        migrations.AddField(
            model_name='entryregime',
            name='regulatory_legal_acts',
            field=models.TextField(blank=True, null=True, verbose_name='Нормативно-правовой акт'),
        ),
    ]
