volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_django_media: {}
  
services:
  django:
    image: tlos205/bghb_production_django
    volumes:
      - production_django_media:/app/bghb/media
    depends_on:
      - postgres
    env_file:
      - .env
    command: /start

  postgres:
    image: postgres:17
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - .env 

  nginx:
    image: tlos205/bghb_production_nginx
    depends_on:
      - django
    volumes:
      - production_django_media:/usr/share/nginx/media:ro
    ports:
      - '8000:80'
      - "443:443" #добавил для проверки