volumes:
  bghb_local_postgres_data: {}
  bghb_local_postgres_data_backups: {}
  

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: bghb_local_django
    container_name: bghb_local_django
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: bghb_production_postgres
    container_name: bghb_local_postgres
    volumes:
      - bghb_local_postgres_data:/var/lib/postgresql/data
      - bghb_local_postgres_data_backups:/backups
      - /Users/artemtkalin/PycharmProjects/new1902/bghb/backups:/backups:z
    env_file:
      - .env
