# Generated by Django 5.0.11 on 2025-02-02 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Код документа')),
                ('name', models.CharField(max_length=255, verbose_name='Название типа документа')),
                ('category', models.CharField(blank=True, max_length=255, null=True, verbose_name='Категория документа')),
                ('type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип документа')),
                ('first_issue_date', models.DateField(blank=True, null=True, verbose_name='Дата первой выдачи')),
                ('valid', models.BooleanField(default=True, verbose_name='Действующий')),
                ('legal_status', models.TextField(blank=True, null=True, verbose_name='Юридический статус/основная цель')),
                ('length', models.FloatField(blank=True, null=True, verbose_name='Длина документа')),
                ('width', models.FloatField(blank=True, null=True, verbose_name='Ширина документа')),
                ('pages', models.IntegerField(blank=True, null=True, verbose_name='Количество страниц')),
                ('validity_period', models.IntegerField(blank=True, null=True, verbose_name='Срок действия')),
                ('renewable', models.BooleanField(default=False, verbose_name='Возможность продления')),
                ('issuing_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='countries.country', verbose_name='Государство, выдающее документ')),
            ],
            options={
                'verbose_name': 'Тип документа',
                'verbose_name_plural': 'Типы документов',
            },
        ),
        migrations.CreateModel(
            name='DocumentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_image', models.BinaryField(blank=True, null=True, verbose_name='Изображение обложки документа')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.documenttype', verbose_name='Тип документа')),
            ],
            options={
                'verbose_name': 'Изображение документа',
                'verbose_name_plural': 'Изображения документов',
            },
        ),
        migrations.CreateModel(
            name='DocumentFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=255, verbose_name='Название особенности')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание особенности')),
                ('image', models.BinaryField(blank=True, null=True, verbose_name='Изображение особенности')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.documenttype', verbose_name='Тип документа')),
            ],
            options={
                'verbose_name': 'Особенность документа',
                'verbose_name_plural': 'Особенности документов',
            },
        ),
    ]
