# Generated by Django 5.0.11 on 2025-02-03 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentfeature',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение особенности'),
        ),
    ]
