# Generated by Django 5.0.11 on 2025-02-03 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_documentfeature_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentfeature',
            name='description',
        ),
        migrations.RemoveField(
            model_name='documentfeature',
            name='image',
        ),
        migrations.AlterField(
            model_name='documentfeature',
            name='document_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='documents.documenttype', verbose_name='Тип документа'),
        ),
        migrations.CreateModel(
            name='FeatureDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, verbose_name='Ключ (например, материал, цвет)')),
                ('value', models.CharField(max_length=255, verbose_name='Значение (например, пластик, красный)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='feature_detail_images/', verbose_name='Изображение')),
                ('document_feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='documents.documentfeature', verbose_name='Особенность')),
            ],
            options={
                'verbose_name': 'Деталь особенности',
                'verbose_name_plural': 'Детали особенностей',
            },
        ),
        migrations.DeleteModel(
            name='DocumentImage',
        ),
    ]
